feat: update devscripts to 2.25.18

diff --git a/test/test_uscan_git b/test/test_uscan_git
--- a/test/test_uscan_git
+++ b/test/test_uscan_git
@@ -32,9 +32,11 @@ export XDG_CONFIG_HOME=""
 #COMMAND="$COMMAND --verbose"
 #COMMAND="$COMMAND --debug"
 
-cleanup(){
+cleanup() {
     rm -rf "$TEMP_PKG_DIR"
 }
+
+trap cleanup EXIT
 
 spawnGitDaemon() {
     [ -n "$TEMP_PKG_DIR" ] || fail "unexpected testsuite error"
@@ -75,7 +77,7 @@ spawnGitRepo() {
     echo 'extra.c export-ignore' >.gitattributes
     chronic_sh git add changelog file.c extra.c .gitattributes
     chronic_sh git commit -a -m 'Init'
-    for version in 1.0 2.0; do
+    for version in 1.0-rc-1 1.0 2.0; do
         echo "# Version $version" >> file.c
         cat >> changelog <<END
 Version $version
@@ -86,16 +88,28 @@ END
     done)
 }
 
-cleanup () {
-    killGitDaemon
-    rm -rf "$TEMP_PKG_DIR"
+spawnGitSubmodule() {
+    spawnGitRepo "srv/${1}.git"
+    touch "$TEMP_PKG_DIR/srv/${1}.git/.git/git-daemon-export-ok"
+    cd "$TEMP_PKG_DIR/repo" || exit 1
+    chronic_sh git submodule add "git://localhost/${1}.git"
+    chronic_sh git commit -a -m "Add submodule: '${1}'"
+    local version="3.0"
+    cat >> changelog <<END
+Version $version
+
+END
+    chronic_sh git commit -a -m "Releasing $version"
+    chronic_sh git tag -s -u 72543FAF -m "Version $version" "v$version"
+    cd - > /dev/null || exit 1
 }
 
-trap cleanup EXIT
-
-containsName(){
-  echo "$1" | grep -F -q "$2"
-  echo $?
+spawnGitUpstreamRemote() {
+    cd "$TEMP_PKG_DIR/$PKG" || exit 1
+    chronic_sh git init
+    chronic_sh git remote add upstream "file:///$TEMP_PKG_DIR/repo"
+    chronic_sh git fetch upstream
+    cd - > /dev/null || exit 1
 }
 
 # shellcheck source=shunit2-helper-functions.sh
@@ -104,13 +118,19 @@ containsName(){
 PKG=foo
 
 writeDebianWatch() {
-    local watchargs="$1"
-    local gitref=${2:-"refs/tags/v([\\d\\.]+)"}
-    cat <<END > "$TEMP_PKG_DIR/$PKG/debian/watch"
-version=4
-opts="mode=git, $watchargs" \
-file:///$TEMP_PKG_DIR/repo $gitref debian
+    local watchargs=$(echo "$1" | sed -r 's/, ?/\n/g')
+    local gitref=${2:-"refs/tags/v([\\d\\.rc-]+)"}
+    local options=$(cat <<END
+Git-Mode: shallow
+Matching-Pattern: ${gitref}
+Mode: git
+Source: file:///${TEMP_PKG_DIR}/repo
+${watchargs}
 END
+)
+
+options=$(echo "${options}" | sort)
+echo -e "Version: 5\n\n${options}" > "$TEMP_PKG_DIR/$PKG/debian/watch"
 }
 
 makeDebianDir() {
@@ -122,7 +142,7 @@ makeDebianDir() {
     mkdir -p "$TEMP_PKG_DIR"/$PKG/debian/upstream
     mkdir -p "$TEMP_PKG_DIR"/$PKG/debian/source
 
-    writeDebianWatch "$1" "${2:-}"
+    writeDebianWatch "${1:-}" "${2:-}"
 
     cat <<END > "$TEMP_PKG_DIR/$PKG/debian/changelog"
 $PKG (0-1) unstable; urgency=low
@@ -135,16 +155,6 @@ END
     cp -f "$test_dir/uscan/PUBLIC_KEY.asc" "$TEMP_PKG_DIR/$PKG/debian/upstream/signing-key.asc"
 }
 
-makeDebianDirWithUpstream() {
-    makeDebianDir "$1"
-    spawnGitRepo
-    cd "$TEMP_PKG_DIR/$PKG" || exit 1
-    chronic_sh git init
-    chronic_sh git remote add upstream "file:///$TEMP_PKG_DIR/repo"
-    chronic_sh git fetch upstream
-    cd - > /dev/null || exit 1
-}
-
 runTest() {
     local cmd_arg="${1:-}"
     ( cd "$TEMP_PKG_DIR/$PKG" || exit 1 ; $COMMAND $cmd_arg --watchfile=debian/watch )
@@ -152,7 +162,7 @@ runTest() {
 }
 
 testGit() {
-    makeDebianDir "gitmode=shallow, pgpmode=none"
+    makeDebianDir "Pgp-Mode: none"
     spawnGitRepo
     runTest
     local tarball=${PKG}_2.0.orig.tar.xz
@@ -163,7 +173,7 @@ testGit() {
 }
 
 testGitHead() {
-    makeDebianDir "pgpmode=none, pretty=0.0+git%cd.%h" "HEAD"
+    makeDebianDir "Pgp-Mode: none, Pretty: 0.0+git%cd.%h" "HEAD"
     spawnGitRepo
     runTest
     local orig=$(find "$TEMP_PKG_DIR" | perl -ne 'print if/\/foo.*\.orig\.tar\.xz$/')
@@ -175,7 +185,7 @@ testGitHead() {
 }
 
 testGitIgnoreExclusions() {
-    makeDebianDir "gitmode=shallow, gitexport=all"
+    makeDebianDir "Git-Export: all"
     spawnGitRepo
     runTest
     assertTrue 'downloaded tarball is incomplete' \
@@ -184,7 +194,7 @@ testGitIgnoreExclusions() {
 }
 
 testGitSignedTag() {
-    makeDebianDir "gitmode=shallow, pgpmode=gittag"
+    makeDebianDir "Pgp-Mode: gittag"
     spawnGitRepo
     runTest
     local tarball=${PKG}_2.0.orig.tar.xz
@@ -195,7 +205,7 @@ testGitSignedTag() {
 }
 
 testGitSignedTagWithDestDir() {
-    makeDebianDir "gitmode=shallow, pgpmode=gittag"
+    makeDebianDir "Pgp-Mode: gittag"
     spawnGitRepo
     local destdir=$TEMP_PKG_DIR/destdir
     mkdir -p $destdir
@@ -208,7 +218,7 @@ testGitSignedTagWithDestDir() {
 }
 
 testGitUncompressed() {
-    makeDebianDir "gitmode=shallow, pgpmode=none"
+    makeDebianDir "Pgp-Mode: none"
     spawnGitRepo
     runTest "--vcs-export-uncompressed"
     local tarball=${PKG}_2.0.orig.tar.xz
@@ -218,8 +228,21 @@ testGitUncompressed() {
     cleanup
 }
 
+testGitVersionMangle() {
+    makeDebianDir "Pgp-Mode: none, Version-Mangle: s/-rc-/~rc-/"
+    spawnGitRepo
+    runTest "--download-version 1.0-rc-1"
+    local tarball=${PKG}_1.0\~rc-1.orig.tar.xz
+    assertTrue 'downloaded tarfile not present' "[ -f '$TEMP_PKG_DIR/${PKG}-1.0-rc-1.tar.xz' ]"
+    assertTrue 'pristine tarball not created' "[ -f '$TEMP_PKG_DIR/$tarball' ]"
+    assertTrue 'pristine tarball should be a symlink' "[ -L '$TEMP_PKG_DIR/$tarball' ]"
+    cleanup
+}
+
 testGitUpstream() {
-    makeDebianDirWithUpstream "gitmode=shallow, pgpmode=none"
+    makeDebianDir "Pgp-Mode: none"
+    spawnGitRepo
+    spawnGitUpstreamRemote
     runTest
     local tarball=${PKG}_2.0.orig.tar.xz
     assertTrue 'downloaded tarfile not present' "[ -f '$TEMP_PKG_DIR/${PKG}-2.0.tar.xz' ]"
@@ -229,7 +252,9 @@ testGitUpstream() {
 }
 
 testGitUpstreamSignedTag() {
-    makeDebianDirWithUpstream "gitmode=shallow, pgpmode=gittag"
+    makeDebianDir "Pgp-Mode: gittag"
+    spawnGitRepo
+    spawnGitUpstreamRemote
     runTest
     local tarball=${PKG}_2.0.orig.tar.xz
     assertTrue 'downloaded tarfile not present' "[ -f '$TEMP_PKG_DIR/${PKG}-2.0.tar.xz' ]"
@@ -239,32 +264,69 @@ testGitUpstreamSignedTag() {
 }
 
 testGitUpstreamIgnoreExclusions() {
-    makeDebianDirWithUpstream "gitmode=shallow, gitexport=all"
+    makeDebianDir "Git-Export: all"
+    spawnGitRepo
+    spawnGitUpstreamRemote
     runTest
     assertTrue 'downloaded tarball is incomplete' \
         "tar tf '$TEMP_PKG_DIR/${PKG}-2.0.tar.xz' '${PKG}-2.0/extra.c'"
     cleanup
 }
 
-testGitSubmodules() {
-    makeDebianDir "gitmodules"
+MODULE1=subrepo
+
+testGitWithSubmodulesInit() {
+    makeDebianDir "Git-Modules: all, Pgp-Mode: none, Pretty: 0.0+git%cd.%h" "HEAD"
     spawnGitRepo
-    local subrepo="subrepo"
-    spawnGitRepo "srv/${subrepo}.git"
-    touch "$TEMP_PKG_DIR/srv/${subrepo}.git/.git/git-daemon-export-ok"
     spawnGitDaemon
-    cd "$TEMP_PKG_DIR/repo" || exit 1
-    chronic_sh git submodule add "git://localhost/${subrepo}.git"
-    chronic_sh git commit -a -m "Add $subrepo module"
+    spawnGitSubmodule ${MODULE1}
+}
+
+testGitHeadWithSubmodules() {
+    runTest
+    local orig_xz=$(find "$TEMP_PKG_DIR" -type l -name "$PKG*" -exec basename {} \;)
+    local upstream_xz=$(find "$TEMP_PKG_DIR" -type f -name "$PKG*" -exec basename {} \;)
+    local version_dir=$(echo "$upstream_xz" | cut -d '.' -f -3)
+    assertTrue "downloaded tarfile not present" "[ -f '$TEMP_PKG_DIR/$upstream_xz' ]"
+    assertTrue "pristine tarball not created" "[ -f '$TEMP_PKG_DIR/$orig_xz' ]"
+    assertTrue "pristine tarball should be a symlink" "[ -L '$TEMP_PKG_DIR/$orig_xz' ]"
+    assertTrue "downloaded tarball is incomplete" \
+        "tar -tf '$TEMP_PKG_DIR/$orig_xz' '${version_dir}/file.c'"
+    assertTrue "downloaded tarball is incomplete; module '${MODULE1}' is missing" \
+        "tar -tf '$TEMP_PKG_DIR/$orig_xz' '${version_dir}/${MODULE1}/file.c'"
+    assertFalse "${version_dir}/extra.c should not be present" \
+        "tar -tf '$TEMP_PKG_DIR/$orig_xz' '${version_dir}/extra.c'"
+    assertFalse "${version_dir}/${MODULE1}/extra.c should not be present" \
+        "tar -tf '$TEMP_PKG_DIR/$orig_xz' '${version_dir}/${MODULE1}/extra.c'"
+    # cleanup() omitted intentionally
+    rm -f "$TEMP_PKG_DIR/$orig_xz" "$TEMP_PKG_DIR/$upstream_xz"
+}
+
+testGitHeadWithSubmodulesIgnoreExclusions() {
+    writeDebianWatch "Git-Export: all, Git-Modules: all, Pgp-Mode: none, Pretty: 0.0+git%cd.%h" "HEAD"
+    runTest
+    local orig_xz=$(find "$TEMP_PKG_DIR" -type l -name "$PKG*" -exec basename {} \;)
+    local upstream_xz=$(find "$TEMP_PKG_DIR" -type f -name "$PKG*" -exec basename {} \;)
+    local version_dir=$(echo "$upstream_xz" | cut -d '.' -f -3)
+    assertTrue "downloaded tarfile not present" \
+        "[ -f '$TEMP_PKG_DIR/$upstream_xz' ]"
+    assertTrue "pristine tarball not created" \
+        "[ -f '$TEMP_PKG_DIR/$orig_xz' ]"
+    assertTrue "pristine tarball should be a symlink" \
+        "[ -L '$TEMP_PKG_DIR/$orig_xz' ]"
+    assertTrue "downloaded tarball is incomplete" \
+        "tar -tf '$TEMP_PKG_DIR/$orig_xz' '${version_dir}/file.c' \
+        '${version_dir}/extra.c'"
+    assertTrue "downloaded tarball is incomplete; module '${MODULE1}' is missing" \
+        "tar -tf '$TEMP_PKG_DIR/$orig_xz' '${version_dir}/${MODULE1}/file.c' \
+        '${version_dir}/${MODULE1}/extra.c'"
+    # cleanup() omitted intentionally
+    rm -f "$TEMP_PKG_DIR/$orig_xz" "$TEMP_PKG_DIR/$upstream_xz"
+}
+
+testGitTagWithSubmodules() {
+    writeDebianWatch "Git-Modules: all"
     local version="3.0"
-    cat >> changelog <<END
-Version $version
-
-END
-    chronic_sh git commit -a -m "Releasing $version"
-    chronic_sh git tag -s -u 72543FAF -m "Version $version" "v$version"
-    cd - > /dev/null || exit 1
-
     local tarball="${PKG}_${version}.orig.tar.xz"
     runTest
     assertTrue "downloaded tarfile not present" \
@@ -275,22 +337,21 @@ END
         "[ -L '$TEMP_PKG_DIR/$tarball' ]"
     assertTrue "downloaded tarball is incomplete" \
         "tar -tf '$TEMP_PKG_DIR/$tarball' '${PKG}-${version}/file.c'"
-    assertTrue "downloaded tarball is incomplete; ${subrepo} missing" \
-        "tar -tf '$TEMP_PKG_DIR/$tarball' '${PKG}-${version}/${subrepo}/file.c'"
+    assertTrue "downloaded tarball is incomplete; module '${MODULE1}' is missing" \
+        "tar -tf '$TEMP_PKG_DIR/$tarball' '${PKG}-${version}/${MODULE1}/file.c'"
     assertFalse "${PKG}-${version}/extra.c should not be present" \
         "tar -tf '$TEMP_PKG_DIR/$tarball' '${PKG}-${version}/extra.c'"
-    assertFalse "${PKG}-${version}/${subrepo}/extra.c should not be present" \
-        "tar -tf '$TEMP_PKG_DIR/$tarball' '${PKG}-${version}/${subrepo}/extra.c'"
-    # killGitDaemon() and cleanup() omitted intentionally
+    assertFalse "${PKG}-${version}/${MODULE1}/extra.c should not be present" \
+        "tar -tf '$TEMP_PKG_DIR/$tarball' '${PKG}-${version}/${MODULE1}/extra.c'"
+    # cleanup() omitted intentionally
     rm -f "$TEMP_PKG_DIR/$tarball" "$TEMP_PKG_DIR/${PKG}-${version}.tar.xz"
 }
 
-testGitSubmodulesIgnoreExclusions() {
-    writeDebianWatch "gitexport=all, gitmodules"
+testGitTagWithSubmodulesIgnoreExclusions() {
+    writeDebianWatch "Git-Export: all, Git-Modules: all"
     runTest
     local version="3.0"
     local tarball="${PKG}_${version}.orig.tar.xz"
-    local subrepo="subrepo"
     assertTrue "downloaded tarfile not present" \
         "[ -f '$TEMP_PKG_DIR/${PKG}-${version}.tar.xz' ]"
     assertTrue "pristine tarball not created" \
@@ -300,9 +361,14 @@ testGitSubmodulesIgnoreExclusions() {
     assertTrue "downloaded tarball is incomplete" \
         "tar -tf '$TEMP_PKG_DIR/$tarball' '${PKG}-${version}/file.c' \
         '${PKG}-${version}/extra.c'"
-    assertTrue "downloaded tarball is incomplete; ${subrepo} missing" \
-        "tar -tf '$TEMP_PKG_DIR/$tarball' '${PKG}-${version}/${subrepo}/file.c' \
-         '${PKG}-${version}/${subrepo}/extra.c'"
+    assertTrue "downloaded tarball is incomplete; module '${MODULE1}' is missing" \
+        "tar -tf '$TEMP_PKG_DIR/$tarball' '${PKG}-${version}/${MODULE1}/file.c' \
+         '${PKG}-${version}/${MODULE1}/extra.c'"
+    # cleanup() omitted intentionally
+    rm -f "$TEMP_PKG_DIR/$tarball" "$TEMP_PKG_DIR/${PKG}-${version}.tar.xz"
+}
+
+testGitWithSubmodulesCleanup() {
     killGitDaemon
     cleanup
 }
